name: Docker Build # Nazwa całej sekcji konfiguracji Docker Build.

on:
  push:
    branches:
      - main # Wykonywanie procesu Docker Build tylko w przypadku push'a do brancha "main".

jobs:
  build:
    runs-on: ubuntu-latest # Wykorzystanie obrazu Ubuntu jako środowiska wykonawczego.

    steps:
      - name: Checkout code # Krok pobrania kodu źródłowego.
        uses: actions/checkout@v2

      - name: Set up QEMU # Konfiguracja QEMU (emulatora).
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx # Konfiguracja Docker Buildx.
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub # Logowanie do Docker Hub.
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Pobranie nazwy użytkownika Docker Hub z secret GitHub.
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Pobranie hasła/tokena Docker Hub z secret GitHub.

      - name: Build and push x86_64 image # Krok budowy i wysyłania obrazu x86_64.
        uses: docker/build-push-action@v2
        with:
          context: . # Kontekst budowy ustawiony na bieżący katalog.
          push: true # Wysyłanie obrazu do Docker Hub.
          tags: zoltig/zadanie2:x86_64 # Etykieta obrazu dla architektury x86_64.

      - name: Build and push arm64 image # Krok budowy i wysyłania obrazu arm64.
        uses: docker/build-push-action@v2
        with:
          context: . # Kontekst budowy ustawiony na bieżący katalog.
          push: true # Wysyłanie obrazu do Docker Hub.
          tags: zoltig/zadanie2:arm64 # Etykieta obrazu dla architektury arm64.
          platform: linux/arm64 # Platforma docelowa dla budowy obrazu arm64.

